# Generated by Django 5.2.17 on 2026-09-11 07:22

import django.contrib.gis.db.models.fields
import django.contrib.postgres.search
from django.contrib.postgres.operations import CreateExtension, TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # Extensions must run before any model creates a PostGIS geometry column
        # or a pg_trgm-backed index — hand-added ahead of the generated CreateModel
        # ops (makemigrations does not emit these).
        CreateExtension("postgis"),
        TrigramExtension(),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('EGID', models.IntegerField(db_column='EGID', primary_key=True, serialize=False)),
                ('GDEKT', models.TextField(db_column='GDEKT', db_index=True, null=True)),
                ('GGDENR', models.IntegerField(db_column='GGDENR', null=True)),
                ('GGDENAME', models.TextField(db_column='GGDENAME', null=True)),
                ('GKODE', models.FloatField(db_column='GKODE', null=True)),
                ('GKODN', models.FloatField(db_column='GKODN', null=True)),
                ('GSTAT', models.IntegerField(db_column='GSTAT', null=True)),
                ('GKAT', models.IntegerField(db_column='GKAT', db_index=True, null=True)),
                ('GKLAS', models.IntegerField(db_column='GKLAS', null=True)),
                ('GBAUJ', models.IntegerField(db_column='GBAUJ', db_index=True, null=True)),
                ('GBAUP', models.IntegerField(db_column='GBAUP', null=True)),
                ('GAREA', models.IntegerField(db_column='GAREA', null=True)),
                ('GVOL', models.IntegerField(db_column='GVOL', null=True)),
                ('GASTW', models.IntegerField(db_column='GASTW', null=True)),
                ('GANZWHG', models.IntegerField(db_column='GANZWHG', null=True)),
                ('GENH1', models.IntegerField(db_column='GENH1', db_index=True, null=True)),
                ('GENH2', models.IntegerField(db_column='GENH2', null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(null=True, srid=2056)),
            ],
            options={
                'db_table': 'building',
            },
        ),
        migrations.CreateModel(
            name='Dwelling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EGID', models.IntegerField(db_column='EGID', db_index=True)),
                ('EWID', models.IntegerField(db_column='EWID', null=True)),
                ('EDID', models.IntegerField(db_column='EDID', null=True)),
                ('WSTWK', models.IntegerField(db_column='WSTWK', null=True)),
                ('WBEZ', models.TextField(db_column='WBEZ', null=True)),
                ('WSTAT', models.IntegerField(db_column='WSTAT', null=True)),
                ('WAREA', models.IntegerField(db_column='WAREA', null=True)),
                ('WAZIM', models.IntegerField(db_column='WAZIM', null=True)),
                ('WKCHE', models.IntegerField(db_column='WKCHE', null=True)),
                ('WBAUJ', models.IntegerField(db_column='WBAUJ', null=True)),
            ],
            options={
                'db_table': 'dwelling',
            },
        ),
        migrations.CreateModel(
            name='Entrance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EGID', models.IntegerField(db_column='EGID', db_index=True)),
                ('EDID', models.IntegerField(db_column='EDID', null=True)),
                ('STRNAME', models.TextField(db_column='STRNAME', null=True)),
                ('STRSP', models.IntegerField(db_column='STRSP', null=True)),
                ('STROFFIZIEL', models.IntegerField(db_column='STROFFIZIEL', null=True)),
                ('DEINR', models.TextField(db_column='DEINR', null=True)),
                ('DPLZ4', models.IntegerField(db_column='DPLZ4', null=True)),
                ('DPLZNAME', models.TextField(db_column='DPLZNAME', null=True)),
                ('DKODE', models.FloatField(db_column='DKODE', null=True)),
                ('DKODN', models.FloatField(db_column='DKODN', null=True)),
                ('address_label', models.TextField(null=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(null=True, srid=2056)),
            ],
            options={
                'db_table': 'entrance',
            },
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CECODID', models.IntegerField(db_column='CECODID')),
                ('CMERKM', models.TextField(db_column='CMERKM')),
                ('CODTXTLD', models.TextField(db_column='CODTXTLD', null=True)),
                ('CODTXTLF', models.TextField(db_column='CODTXTLF', null=True)),
                ('CODTXTLI', models.TextField(db_column='CODTXTLI', null=True)),
            ],
            options={
                'db_table': 'code',
                'indexes': [models.Index(fields=['CMERKM', 'CECODID'], name='code_CMERKM_b2ba17_idx')],
            },
        ),
    ]
