# Generated by Django 5.2.17 on 2026-09-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwr', '0004_stats_dimkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='GEBF',
            field=models.IntegerField(db_column='GEBF', null=True),
        ),
    ]
