FIELD_LABELS: dict[str, str] = {
    # building
    "EGID": "Eidg. Gebäudeidentifikator (Gebäude-ID)",
    "GDEKT": "Kanton",
    "GGDENR": "BFS-Gemeindenummer",
    "GGDENAME": "Gemeindename",
    "EGRID": "Eidg. Grundstücksidentifikator",
    "LGBKR": "Grundbuchkreisnummer",
    "LPARZ": "Grundstücksnummer",
    "LPARZSX": "Suffix der Grundstücksnummer",
    "LTYP": "Typ des Grundstücks",
    "GEBNR": "Amtliche Gebäudenummer",
    "GBEZ": "Name des Gebäudes",
    "GKODE": "E-Gebäudekoordinate (Ost, LV95)",
    "GKODN": "N-Gebäudekoordinate (Nord, LV95)",
    "GKSCE": "Koordinatenherkunft",
    "GSTAT": "Gebäudestatus",
    "GKAT": "Gebäudekategorie",
    "GKLAS": "Gebäudeklasse",
    "GBAUJ": "Baujahr des Gebäudes",
    "GBAUM": "Baumonat des Gebäudes",
    "GBAUP": "Bauperiode",
    "GABBJ": "Abbruchjahr des Gebäudes",
    "GAREA": "Gebäudefläche (m²)",
    "GVOL": "Gebäudevolumen (m³)",
    "GVOLNORM": "Gebäudevolumen: Norm",
    "GVOLSCE": "Informationsquelle zum Gebäudevolumen",
    "GASTW": "Anzahl Geschosse",
    "GANZWHG": "Anzahl Wohnungen",
    "GAZZI": "Anzahl separate Wohnräume",
    "GSCHUTZR": "Zivilschutzraum",
    "GEBF": "Energiebezugsfläche",
    "GWAERZH1": "Wärmeerzeuger Heizung 1",
    "GWAERZH2": "Wärmeerzeuger Heizung 2",
    "GENH1": "Energie-/Wärmequelle Heizung 1",
    "GENH2": "Energie-/Wärmequelle Heizung 2",
    "GWAERSCEH1": "Informationsquelle Heizung 1",
    "GWAERSCEH2": "Informationsquelle Heizung 2",
    "GWAERDATH1": "Aktualisierungsdatum Heizung 1",
    "GWAERDATH2": "Aktualisierungsdatum Heizung 2",
    "GWAERZW1": "Wärmeerzeuger Warmwasser 1",
    "GWAERZW2": "Wärmeerzeuger Warmwasser 2",
    "GENW1": "Energie-/Wärmequelle Warmwasser 1",
    "GENW2": "Energie-/Wärmequelle Warmwasser 2",
    "GWAERSCEW1": "Informationsquelle Warmwasser 1",
    "GWAERSCEW2": "Informationsquelle Warmwasser 2",
    "GWAERDATW1": "Aktualisierungsdatum Warmwasser 1",
    "GWAERDATW2": "Aktualisierungsdatum Warmwasser 2",
    "GEXPDAT": "Exportdatum",
    # entrance
    "EDID": "Eidg. Eingangsidentifikator (Eingangs-ID)",
    "EGAID": "Eidg. Gebäudeadressidentifikator",
    "DEINR": "Eingangsnummer Gebäude (Hausnummer)",
    "ESID": "Eidg. Strassenidentifikator",
    "STRNAME": "Strassenbezeichnung",
    "STRNAMK": "Strassenbezeichnung kurz",
    "STRINDX": "Strassenbezeichnung Index",
    "STRSP": "Strassenbezeichnung Sprache",
    "STROFFIZIEL": "Strassenbezeichnung offiziell",
    "DPLZ4": "Postleitzahl",
    "DPLZZ": "Postleitzahl-Zusatzziffer",
    "DPLZNAME": "Ortschaftsname (PLZ)",
    "DKODE": "E-Eingangskoordinate (Ost, LV95)",
    "DKODN": "N-Eingangskoordinate (Nord, LV95)",
    "DOFFADR": "Offizielle Adresse",
    "DEXPDAT": "Exportdatum",
    # dwelling
    "EWID": "Eidg. Wohnungsidentifikator (Wohnungs-ID)",
    "WHGNR": "Administrative Wohnungsnummer",
    "WEINR": "Physische Wohnungsnummer",
    "WSTWK": "Stockwerk",
    "WBEZ": "Lage auf dem Stockwerk",
    "WMEHRG": "Mehrgeschossige Wohnung",
    "WBAUJ": "Baujahr der Wohnung",
    "WABBJ": "Abbruchjahr der Wohnung",
    "WSTAT": "Wohnungsstatus",
    "WAREA": "Wohnungsfläche (m²)",
    "WAZIM": "Anzahl Zimmer",
    "WKCHE": "Kocheinrichtung",
    "WEXPDAT": "Exportdatum",
}


def field_label(name: str) -> str:
    return FIELD_LABELS.get(name, name)
