# Generated by Django 5.2.17 on 2026-09-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('EGID', models.IntegerField(db_column='EGID', primary_key=True, serialize=False)),
                ('GDEKT', models.TextField(db_column='GDEKT', null=True)),
                ('GGDENR', models.IntegerField(db_column='GGDENR', null=True)),
                ('GGDENAME', models.TextField(db_column='GGDENAME', null=True)),
                ('GKODE', models.FloatField(db_column='GKODE', null=True)),
                ('GKODN', models.FloatField(db_column='GKODN', null=True)),
                ('GSTAT', models.IntegerField(db_column='GSTAT', null=True)),
                ('GKAT', models.IntegerField(db_column='GKAT', null=True)),
                ('GKLAS', models.IntegerField(db_column='GKLAS', null=True)),
                ('GBAUJ', models.IntegerField(db_column='GBAUJ', null=True)),
                ('GBAUP', models.IntegerField(db_column='GBAUP', null=True)),
                ('GAREA', models.IntegerField(db_column='GAREA', null=True)),
                ('GVOL', models.IntegerField(db_column='GVOL', null=True)),
                ('GASTW', models.IntegerField(db_column='GASTW', null=True)),
                ('GANZWHG', models.IntegerField(db_column='GANZWHG', null=True)),
                ('GENH1', models.IntegerField(db_column='GENH1', null=True)),
                ('GENH2', models.IntegerField(db_column='GENH2', null=True)),
            ],
            options={
                'db_table': 'building',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.IntegerField(db_column='rowid', primary_key=True, serialize=False)),
                ('CECODID', models.IntegerField(db_column='CECODID')),
                ('CMERKM', models.TextField(db_column='CMERKM')),
                ('CODTXTLD', models.TextField(db_column='CODTXTLD', null=True)),
            ],
            options={
                'db_table': 'code',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dwelling',
            fields=[
                ('id', models.IntegerField(db_column='rowid', primary_key=True, serialize=False)),
                ('EGID', models.IntegerField(db_column='EGID')),
                ('EWID', models.IntegerField(db_column='EWID', null=True)),
                ('EDID', models.IntegerField(db_column='EDID', null=True)),
                ('WSTWK', models.IntegerField(db_column='WSTWK', null=True)),
                ('WBEZ', models.TextField(db_column='WBEZ', null=True)),
                ('WSTAT', models.IntegerField(db_column='WSTAT', null=True)),
                ('WAREA', models.IntegerField(db_column='WAREA', null=True)),
                ('WAZIM', models.IntegerField(db_column='WAZIM', null=True)),
                ('WKCHE', models.IntegerField(db_column='WKCHE', null=True)),
                ('WBAUJ', models.IntegerField(db_column='WBAUJ', null=True)),
            ],
            options={
                'db_table': 'dwelling',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entrance',
            fields=[
                ('id', models.IntegerField(db_column='rowid', primary_key=True, serialize=False)),
                ('EGID', models.IntegerField(db_column='EGID')),
                ('EDID', models.IntegerField(db_column='EDID', null=True)),
                ('DEINR', models.TextField(db_column='DEINR', null=True)),
                ('STRNAME', models.TextField(db_column='STRNAME', null=True)),
                ('DPLZ4', models.IntegerField(db_column='DPLZ4', null=True)),
                ('DPLZNAME', models.TextField(db_column='DPLZNAME', null=True)),
                ('DKODE', models.FloatField(db_column='DKODE', null=True)),
                ('DKODN', models.FloatField(db_column='DKODN', null=True)),
            ],
            options={
                'db_table': 'entrance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MapPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('egid', models.IntegerField(db_index=True)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('canton', models.CharField(db_index=True, max_length=2, null=True)),
                ('gkat', models.IntegerField(db_index=True, null=True)),
                ('gbauj', models.IntegerField(db_index=True, null=True)),
                ('genh1', models.IntegerField(db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(db_index=True, max_length=64)),
                ('dim_key', models.CharField(max_length=128)),
                ('dim_label', models.CharField(max_length=255)),
                ('value', models.FloatField()),
            ],
            options={
                'indexes': [models.Index(fields=['metric'], name='src_statsca_metric_31a3b8_idx')],
            },
        ),
    ]
