# Generated by Django 5.2.17 on 2026-09-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mappoint',
            index=models.Index(fields=['lat', 'lon'], name='src_mappoin_lat_46b2ab_idx'),
        ),
    ]
